### PR TITLE
Import from 1.0 to 5.3.0-rc3

### PR DESCRIPTION
**Pull request by KateAdams**
Solves #3.

### CODE REVIEW

**Comment by craigbarnes** [comment]
Awesome. Thanks for this!

**Comment by neico** [comment]
I hope there will be also branches of it, there are still people using 5.0 and 5.1.

**Comment by craigbarnes** [comment]
@neico You mean branches for diverging point releases. Or something else?

**Comment by neico** [comment]
well we already have a branch for 5.2, so we'd need at least one for 5.1 and 5.3 once it's out.

**Comment by craigbarnes** [comment]
Oh, that `5.2` branch was from before this pull request was merged. I've just deleted it, since it's no longer relevant with this new history.

Could you be more specific about what you want branches for..?

**Comment by neico** [comment]
Well branches are important for different milestones, and 5.1 differs heavily from 5.2 (which is why many refuse to use 5.2, see LuaJit), and 5.3 might be the next big change that developers will not use for a while, so until those versions are officially unsupported or the majority actually moves to the newer ones I'd suggest keeping branches of them (as I for example only use the 5.2 branch since I welcome those new changes)

a branch is most useful when older versions still or might receive patches from upstream.
(for 5.1 I'm not too sure that'll happen but I know at least some bigger instances still using it)

**Comment by KateAdams** [comment]
Hmm, maybe we can tag each release?

So you can go:

```sh
[master] $ git checkout -b my-branch 5.1.15
[my-branch] $ 
```

**Comment by craigbarnes** [comment]
> Well branches are important for different milestones

Important how? For what purpose? Each commit already directly corresponds to a release.

I'm still planning to write a script to generate the history automatically/reproducably, which I will put in another repo. For that, I will use branches only when the history actually diverges, to keep the order of commits the same as the order of releases.

**Comment by hishamhm** [comment]
I was going to post an issue asking for tags for each release :)

And yes, branches for each x.y release make sense, since as @craigbarnes said, 5.1.5 came out after 5.2.0, and there will most likely be a 5.2.4 fixing all [known bugs](http://www.lua.org/bugs.html).

**Comment by daurnimator** [comment]
Missed some e.g. 5.1.4

Also, releases were not linear; bug fix releases occur after the next release.

Could you set the commit author to Roberto, and use the correct dates?

**Comment by craigbarnes** [comment]
I've just pushed a new history, as generated by https://github.com/lua/repogen.

@hishamhm All commits are tagged now.

@daurnimator 5.1.4 is commit 7c4de52b. The author for all commits is now `Lua Team <team at lua.org>`. Dates are set according to the dates on the [releases] page.

The branched/non-linear releases (5.0.3, 5.1.5, 5.2.4) aren't in the repo yet. I'll handle these in the repogen Makefile and push them as branches soon.

[releases]: http://www.lua.org/ftp/

**Comment by hishamhm** [comment]
@craigbarnes, cool! 

Since you scripted the process, might be a good idea to include these as well: http://www.lua.org/work/old/index.htm

**Pull request merged**
