### PR TITLE
Improved math of lua

### PR DESCRIPTION
**Pull request by TARPTAEYA**
I observed that all math functions are able to take more arguments than required, so I hope I fixed them and added a gcd function to math as I hope making a rich build in library attracts more users. If I miss something or there is some other issue please tell me.

### CODE REVIEW

**Comment by daurnimator** [comment]
Patches are not accept here. Please post your patch to the lua mailing list for discussion.

**Comment by TARPTAEYA** [comment]
ok, thanks

**Comment by giann** [comment]
@daurnimator I think you can disable PR in github's settings

**Comment by daurnimator** [comment]
> @daurnimator I think you can disable PR in github's settings

github allows disabling issues; but not disabling PRs.

**Pull request closed without merging**
